import "./globals.css";
import { ReactNode } from "react";
import ApolloProviderWrapper from "./apollo-provider";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
